Repository t-i-0414/react-reversi, pull requests merged in 2021-01, with the labels that each got.

#27 useEffectを使ってゲーム開始時の石の配置を実装。ひっくり返せる石があるマスのみonClickマスをレンダリング
  src/components/organisms/Board.tsx
Labels: container

#28 release→develop useEffectを使ってゲーム開始時の石の配置を実装。ひっくり返せる石があるマスのみonClickマスをレンダリング
  src/components/organisms/Board.tsx
Labels: container

#29 develop→master useEffectを使ってゲーム開始時の石の配置を実装。ひっくり返せる石があるマスのみonClickマスをレンダリング
  src/components/organisms/Board.tsx
Labels: container

#31 Change README.md from Japanese to English
  .prettierignore
  README.md
Labels: documentation

#32 develop→master Change README.md from Japanese to English
  .prettierignore
  README.md
Labels: documentation

#33 make new Board container file
  src/containers/organisms/Board.tsx
Labels: container

#34 divide Board component into container and component
  src/components/organisms/Board.tsx
  src/components/pages/Game.tsx
  src/const/index.ts
  src/const/player-val.ts
  src/containers/organisms/Board.tsx
  src/hooks/use-board.tsx
  src/utils/index.ts
Labels: component, container

#35 develop→master divide Board component into container and component
  src/components/organisms/Board.tsx
  src/components/pages/Game.tsx
  src/const/index.ts
  src/const/player-val.ts
  src/containers/organisms/Board.tsx
  src/hooks/use-board.tsx
  src/utils/index.ts
Labels: component, container

#37 Rename function and variable names for consistency
  src/containers/organisms/Board.tsx
  src/hooks/use-board.tsx
  src/types/index.ts
Labels: container

#38 develop→master Rename function and variable names for consistency
  src/containers/organisms/Board.tsx
  src/hooks/use-board.tsx
  src/types/index.ts
Labels: container

#39 Turn some comments in the useBoard hook into English
  src/containers/organisms/Board.tsx
  src/hooks/use-board.tsx
Labels: container, documentation

#40 develop→master Turn some comments in the useBoard hook into English
  src/containers/organisms/Board.tsx
  src/hooks/use-board.tsx
Labels: container, documentation

#41 The rest of comments in the useBoard hook into English
  src/hooks/use-board.tsx
Labels: documentation

#42 develop→master The rest of comments in the useBoard hook into English
  src/hooks/use-board.tsx
Labels: documentation

#43 Turn Comments in this App into English
  src/components/pages/Game.tsx
  src/const/player-val.ts
  src/const/size.ts
  src/hooks/use-board.tsx
  src/types/index.ts
Labels: documentation

#44 develop→master Turn Comments in this App into English
  src/components/pages/Game.tsx
  src/const/player-val.ts
  src/const/size.ts
  src/hooks/use-board.tsx
  src/types/index.ts
Labels: documentation

#45 Change module loading way to absolute path
  src/components/atoms/Piece.tsx
  src/components/atoms/Square.tsx
  src/components/organisms/Board.tsx
  src/components/pages/Game.tsx
  src/const/index.ts
  src/containers/organisms/Board.tsx
  src/hooks/use-board.tsx
  src/index.tsx
  src/types/index.ts
  tsconfig.json
Labels: component, container

#46 develop→master Change module loading way to absolute path
  src/components/atoms/Piece.tsx
  src/components/atoms/Square.tsx
  src/components/organisms/Board.tsx
  src/components/pages/Game.tsx
  src/const/index.ts
  src/containers/organisms/Board.tsx
  src/hooks/use-board.tsx
  src/index.tsx
  src/types/index.ts
  tsconfig.json
Labels: component, container

#47 Install cypress to this project
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/examples/actions.spec.js
  cypress/integration/examples/aliasing.spec.js
  cypress/integration/examples/assertions.spec.js
  cypress/integration/examples/connectors.spec.js
  cypress/integration/examples/cookies.spec.js
  cypress/integration/examples/cypress_api.spec.js
  cypress/integration/examples/files.spec.js
  cypress/integration/examples/local_storage.spec.js
  cypress/integration/examples/location.spec.js
  cypress/integration/examples/misc.spec.js
  cypress/integration/examples/navigation.spec.js
  cypress/integration/examples/network_requests.spec.js
  cypress/integration/examples/querying.spec.js
  cypress/integration/examples/spies_stubs_clocks.spec.js
  cypress/integration/examples/traversal.spec.js
  cypress/integration/examples/utilities.spec.js
  cypress/integration/examples/viewport.spec.js
  cypress/integration/examples/waiting.spec.js
  cypress/integration/examples/window.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package.json
  yarn.lock
Labels: test

#48 Fix Comments
  src/hooks/use-board.tsx
Labels: documentation

#49 Initialize cypress
  .eslintignore
  cypress.json
  cypress/integration/game.spec.js
  package.json
Labels: test

#50 develop→master
  .eslintignore
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/examples/actions.spec.js
  cypress/integration/examples/aliasing.spec.js
  cypress/integration/examples/assertions.spec.js
  cypress/integration/examples/connectors.spec.js
  cypress/integration/examples/cookies.spec.js
  cypress/integration/examples/cypress_api.spec.js
  cypress/integration/examples/files.spec.js
  cypress/integration/examples/local_storage.spec.js
  cypress/integration/examples/location.spec.js
  cypress/integration/examples/misc.spec.js
  cypress/integration/examples/navigation.spec.js
  cypress/integration/examples/network_requests.spec.js
  cypress/integration/examples/querying.spec.js
  cypress/integration/examples/spies_stubs_clocks.spec.js
  cypress/integration/examples/traversal.spec.js
  cypress/integration/examples/utilities.spec.js
  cypress/integration/examples/viewport.spec.js
  cypress/integration/examples/waiting.spec.js
  cypress/integration/examples/window.spec.js
  cypress/integration/game.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package.json
  src/hooks/use-board.tsx
  yarn.lock
Labels: documentation, test

#51 cypress tutorial
  cypress/integration/game.spec.js
Labels: test

#52 Add comment to cypress
  cypress/integration/game.spec.js
Labels: documentation

#53 develop→master Install cypress
  cypress/integration/game.spec.js
Labels: test

#54 Add Github Actions that runs cypress on cli
  cypress/videos/game.spec.js.mp4
  package.json
  test.yml
Labels: CI/CD, test

#55 Modify the Github Actions file's hierarchy
  .github/workflows/test.yml
Labels: CI/CD, test

#56 Modify the Github Actions ubuntu version
  .github/workflows/test.yml
Labels: CI/CD, test

#57 Modify the Github Actions
  .github/workflows/test.yml
Labels: CI/CD, test

#58 develop→master Add Github Actions that runs cypress on cli
  .github/workflows/test.yml
  cypress/videos/game.spec.js.mp4
  package.json
Labels: CI/CD, test

#59 Fix github actions jobs name
  .github/workflows/test.yml
Labels: CI/CD, test

#60 develop→master Fix github actions jobs name
  .github/workflows/test.yml
Labels: CI/CD, test

#63 Add cypress test
  cypress/integration/game.spec.js
Labels: test

#64 Divide Game Component to Container and Component & Make Button Container and Component
  src/components/atoms/Button.tsx
  src/components/pages/Game.tsx
  src/containers/atoms/Button.tsx
  src/containers/pages/Game.tsx
  src/index.tsx
Labels: component, container

#65 Add attributes to HTML Components for Cypress
  cypress/integration/game.spec.js
  cypress/videos/game.spec.js.mp4
  package.json
  src/components/atoms/Button.tsx
  src/components/atoms/Piece.tsx
  src/components/atoms/Square.tsx
  src/components/organisms/Board.tsx
  src/containers/atoms/Button.tsx
  src/containers/organisms/Board.tsx
  src/containers/pages/Game.tsx
Labels: component, container, test

#66 Add basic game test
  cypress/integration/game.spec.js
  src/components/atoms/Piece.tsx
  src/containers/organisms/Board.tsx
Labels: test

#67 Add basic game test and so on
  cypress/integration/game.spec.js
  cypress/videos/game.spec.js.mp4
  package.json
  src/components/atoms/Button.tsx
  src/components/atoms/Piece.tsx
  src/components/atoms/Square.tsx
  src/components/organisms/Board.tsx
  src/components/pages/Game.tsx
  src/containers/atoms/Button.tsx
  src/containers/organisms/Board.tsx
  src/containers/pages/Game.tsx
  src/index.tsx
Labels: component, container, test

#68 Remove comments in game.spec.js
  cypress/integration/game.spec.js
Labels: test

#69 Update cypress Game 'App exists'
  cypress/integration/game.spec.js
  src/components/pages/Game.tsx
  src/containers/pages/Game.tsx
  src/index.tsx
Labels: component, container, test

#70 Add negative integration test
  cypress/integration/game.spec.js
Labels: test

#71 Add style to Game start button
  src/components/atoms/Button.tsx
Labels: component

#72 develop→master
  cypress/integration/game.spec.js
  src/components/atoms/Button.tsx
  src/components/pages/Game.tsx
  src/containers/pages/Game.tsx
  src/index.tsx
Labels: component, test

#73 Enhance button style
  src/components/atoms/Button.tsx
  src/const/color.ts
Labels: component

#74 develop→master Add button styles
  src/components/atoms/Button.tsx
  src/const/color.ts
Labels: component

#75 Add Incoming Webhook
  .github/workflows/test.yml
Labels: CI/CD

#76 Turn PULL_REQUEST template into English
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#77 Turn PULL_REQUEST template into English
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/test.yml
Labels: documentation

#78 Complete dividing component structure
  src/components/atoms/Button/component.tsx
  src/components/atoms/Button/container.tsx
  src/components/atoms/Piece.tsx
  src/components/atoms/Piece/component.tsx
  src/components/atoms/Piece/container.tsx
  src/components/atoms/Square/component.tsx
  src/components/organisms/Board/component.tsx
  src/components/organisms/Board/container.tsx
  src/components/organisms/Board/hook.tsx
  src/components/pages/Game/component.tsx
  src/components/pages/Game/container.tsx
  src/index.tsx
Labels: component, container

#80 Modify Slack Channel for Github Actions Notification
  .github/workflows/test.yml
Labels: CI/CD, test
