Repository t-i-0414/react-reversi, pull requests merged in 2021-06, with the labels that each got.

#160 Add logic where game is finished
  cypress/integration/game.spec.ts
  src/components/pages/game/hooks.ts
  src/components/pages/game/index.tsx
  src/utils/game.ts
Labels: component, enhance

#161 Update README.md
  README.md
Labels: documentation

#162 Add logic where game is finished
  package.json
  src/components/atoms/button/__snapshots__/index.test.tsx.snap
  src/components/atoms/button/index.tsx
  src/components/molecules/reset-modal/__snapshots__/index.test.tsx.snap
  src/components/molecules/reset-modal/hooks.ts
  src/components/molecules/reset-modal/index.stories.tsx
  src/components/molecules/reset-modal/index.test.tsx
  src/components/molecules/reset-modal/index.tsx
  src/components/organisms/setting-form/index.tsx
  src/components/pages/game/index.tsx
  src/const/color.ts
  src/redux/modules/game.ts
  yarn.lock
Labels: component, enhance

#163 Release/1.7.0/2021-06
  cypress/integration/game.spec.ts
  package.json
  src/components/atoms/button/__snapshots__/index.test.tsx.snap
  src/components/atoms/button/index.tsx
  src/components/molecules/reset-modal/__snapshots__/index.test.tsx.snap
  src/components/molecules/reset-modal/hooks.ts
  src/components/molecules/reset-modal/index.stories.tsx
  src/components/molecules/reset-modal/index.test.tsx
  src/components/molecules/reset-modal/index.tsx
  src/components/organisms/setting-form/index.tsx
  src/components/pages/game/hooks.ts
  src/components/pages/game/index.tsx
  src/const/color.ts
  src/redux/modules/game.ts
  src/utils/game.ts
  yarn.lock
Labels: release

#165 Update README.md
  README.md
Labels: documentation
